{
 "title": "硬盘状态监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(megacli_controller,job)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(megacli_controller{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "硬盘告警总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "硬盘 Critical 告警",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "megacli_drives{type=\"physical\",state=\"Critical\"} >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "硬盘 Failed 告警",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "megacli_drives{type=\"physical\",state=\"Failed\"} >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Media Error Count(媒体错误)",
   "type": "table",
   "description": "媒体错误通常是由于硬盘表面的物理损坏或缺陷造成的。\n较高的媒体错误计数可能表明硬盘存在严重问题，可能需要更换。持续增加的媒体错误也是一个警告信号，表明驱动器即将失败。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "megacli_pd_errors{type=\"media\",job=\"$job\"} >0"
    }
   ]
  },
  {
   "title": "Disk other Error Count（其他错误）",
   "type": "table",
   "description": "记录了除媒体错误外其他类型的错误次数。这些可能包括与接口相关的错误（如通信故障）、固件问题或其他非媒体相关的硬件故障。\n重要性：此计数提供了除常规读写操作以外其他潜在问题的视角。虽然单个“其他错误”可能不严重，但数量大或快速增长可能指示存在更广泛的问题。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "megacli_pd_errors{type=\"other\",job=\"$job\"} >0"
    }
   ]
  },
  {
   "title": "Disk Predictive Error Count（智能预测故障）",
   "type": "table",
   "description": "定义：Predictive Failure Count 是智能监控系统预测硬盘即将发生故障时记录的计数。此参数基于多种因素，如硬盘运行温度、运行时间和特定硬件事件。\n重要性：如果预测失败计数上升，这是一个强烈信号，提示即将发生硬件故障。系统管理员应立即采取措施备份数据并考虑替换受影响的驱动器以防止数据丢失。",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "megacli_pd_errors{type=\"predictive\",job=\"$job\"} >0"
    }
   ]
  },
  { "title": "主机硬盘详细信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "物理磁盘状态统计",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "megacli_drives{instance=~\"$node\",type=\"physical\",state=\"PhysicalTotal\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "megacli_drives{instance=~\"$node\",type=\"physical\",state=\"DisksTotal\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "megacli_drives{instance=~\"$node\",type=\"physical\",state=\"Critical\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "megacli_drives{instance=~\"$node\",type=\"physical\",state=\"Failed\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "虚拟磁盘状态统计（Raid Group）",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "megacli_drives{instance=~\"$node\",type=\"virtual\",state=\"Total\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "megacli_drives{instance=~\"$node\",type=\"virtual\",state=\"Degraded\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "megacli_drives{instance=~\"$node\",type=\"virtual\",state=\"Offline\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "磁盘信息",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "megacli_pd_info{job=~\"$job\",instance=~\"$node\",type=\"disk_group\"}"
    },
    {
     "expr": "megacli_pd_info{job=~\"$job\",instance=~\"$node\",type=\"wwn\"}"
    },
    {
     "expr": "megacli_pd_info{job=~\"$job\",instance=~\"$node\",type=\"size_raw\"}"
    },
    {
     "expr": "megacli_pd_info{job=~\"$job\",instance=~\"$node\",type=\"smart_alert\"}"
    },
    {
     "expr": "megacli_pd_speed_bits{job=~\"$job\",instance=~\"$node\",type=\"drive\"}"
    }
   ]
  },
  {
   "title": "Adapter RAID Temperature °C",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "megacli_controller_temperature_celsius{job=~\"$job\",instance=~\"$node\"}",
     "legendFormat": "adapter-{{adapter}}"
    }
   ]
  },
  {
   "title": "Physical drive temperature °C",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "megacli_pd_temperature{job=~\"$job\",instance=~\"$node\",type=\"celsius\"}",
     "legendFormat": "adapter{{adapter}}-slot{{slot}}"
    }
   ]
  },
  {
   "title": "控制器内存信息",
   "type": "graph",
   "description": "Controler memory information",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "megacli_memory_size_bytes{job=~\"$job\",instance=~\"$node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "控制器内存错误信息",
   "type": "graph",
   "description": "Controler memory information",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "megacli_memory_errors{job=~\"$job\",instance=~\"$node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "硬盘media error 趋势图",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "megacli_pd_errors{job=~\"$job\",instance=~\"$node\",type=\"media\"}",
     "legendFormat": "{{adapter}}-{{enclosure}}-{{slot}}"
    }
   ]
  },
  {
   "title": "硬盘other error 趋势图",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "megacli_pd_errors{job=~\"$job\",instance=~\"$node\",type=\"other\"}",
     "legendFormat": "{{adapter}}-{{enclosure}}-{{slot}}"
    }
   ]
  },
  {
   "title": "硬盘predictive error 趋势图",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "megacli_pd_errors{job=~\"$job\",instance=~\"$node\",type=\"predictive\"}",
     "legendFormat": "{{adapter}}-{{enclosure}}-{{slot}}"
    }
   ]
  }
 ]
}